conf = {
  name: 'onet_1',
  filename: 'ONET_Take1.csv',
  questions: [
    'Build kitchen cabinets [Back translation in English:]',
    'Lay brick or tile [Back translation in English:]',
    'Develop a new medicine [Back translation in English:]',
    'Study ways to reduce water pollution [Back translation in English:]',
    'Write books or plays [Back translation in English:]',
    'Play a musical instrument [Back translation in English:]',
    'Teach an individual an exercise routine [Back translation in English:]',
    'Help people with personal or emotional problems [Back translation in English:]',
    'Buy and sell stocks and bonds [Back translation in English:]',
    'Manage a retail store [Back translation in English:]',
    'Develop a spreadsheet using computer software [Back translation in English:]',
    'Proofread records or forms [Back translation in English:]',
    'Repair household appliances [Back translation in English:]',
    'Raise fish in a fish hatchery [Back translation in English:]',
    'Conduct chemical experiments [Back translation in English:]',
    'Study the movement of planets [Back translation in English:]',
    'Compose or arrange music [Back translation in English:]',
    'Draw pictures [Back translation in English:]',
    'Give career guidance to people [Back translation in English:]',
    'Perform rehabilitation therapy [Back translation in English:]',
    'Operate a beauty salon or barber shop [Back translation in English:]',
    'Manage a department within a large company [Back translation in English:]',
    'Load computer software into a large computer network [Back translation in English:]',
    'Operate a calculator [Back translation in English:]',
    'Assemble electronic parts [Back translation in English:]',
    'Drive a truck to deliver packages to offices and homes [Back translation in English:]',
    'Examine blood samples using a microscope [Back translation in English:]',
    'Investigate the cause of a fire [Back translation in English:]',
    'Create special effects for movies [Back translation in English:]',
    'Paint sets for plays [Back translation in English:]',
    'Do volunteer work at a non-profit organization [Back translation in English:]',
    'Teach children how to play sports [Back translation in English:]',
    'Start your own business [Back translation in English:]',
    'Negotiate business contracts [Back translation in English:]',
    'Keep shipping and receiving records [Back translation in English:]',
    'Calculate the wages of employees [Back translation in English:]',
    'Test the quality of parts before shipment [Back translation in English:]',
    'Repair and install locks [Back translation in English:]',
    'Develop a way to better predict the weather [Back translation in English:]',
    'Work in a biology lab [Back translation in English:]',
    'Write scripts for movies or television shows [Back translation in English:]',
    'Perform jazz or tap dance [Back translation in English:]',
    'Teach sign language to people with hearing disabilities [Back translation in English:]',
    'Help conduct a group therapy session [Back translation in English:]',
  ],
  tokenCol: 'Token',
  dateCol: 'Date last action',
  ip: 'IP address',
};

module.exports = conf;
