conf = {
  filename: 'ONET_Take2.csv',
  questions: [
    'Build kitchen cabinets [Back translation in English:]',
    'Write books or plays [Back translation in English:]',
    'Play a musical instrument [Back translation in English:]',
    'Teach an individual an exercise routine [Back translation in English:]',
    'Develop a spreadsheet using computer software [Back translation in English:]',
    'Raise fish in a fish hatchery [Back translation in English:]',
    'Conduct chemical experiments [Back translation in English:]',
    'Study the movement of planets [Back translation in English:]',
    'Compose or arrange music [Back translation in English:]',
    'Perform rehabilitation therapy [Back translation in English:]',
    'Operate a beauty salon or barber shop [Back translation in English:]',
    'Load computer software into a large computer network [Back translation in English:]',
    'Operate a calculator [Back translation in English:]',
    'Assemble electronic parts [Back translation in English:]',
    'Drive a truck to deliver packages to offices and homes [Back translation in English:]',
    'Create special effects for movies [Back translation in English:]',
    'Start your own business [Back translation in English:]',
    'Calculate the wages of employees [Back translation in English:]',
    'Repair and install locks [Back translation in English:]',
    'Develop a way to better predict the weather [Back translation in English:]',
    'Work in a biology lab [Back translation in English:]',
    'Perform jazz or tap dance [Back translation in English:]',
    'Help conduct a group therapy session [Back translation in English:]',
    'Represent a client in a lawsuit [Back translation in English:]',
    'Market a new line of clothing [Back translation in English:]',
    'Set up and operate machines to make products [Back translation in English:]',
    'Invent a replacement for sugar [Back translation in English:]',
    'Do laboratory tests to identify diseases [Back translation in English:]',
    'Sing in a band [Back translation in English:]',
    'REALISTIC [Back translation in English:]',
    'INVESTIGATIVE [Back translation in English:]',
    'ARTISTIC [Back translation in English:]',
    'SOCIAL [Back translation in English:]',
    'ENTERPRISING [Back translation in English:]',
    'CONVENTIONAL [Back translation in English:]',
    'STRONGLYLIKE [Back translation in English:]',
    'LIKE [Back translation in English:]',
    'UNSURE [Back translation in English:]',
    'DISLIKE [Back translation in English:]',
    'STRONGLYDISLIKE [Back translation in English:]',
    'jobzone1 [Back translation in English:]',
    'jobzone2 [Back translation in English:]',
    'jobzone3 [Back translation in English:]',
    'jobzone4 [Back translation in English:]',
    'jobzone5 [Back translation in English:]',
    'currentfuture [Back translation in English:]',
    'Explore [Back translation in English:]',
    'JZcareer [Back translation in English:]',
    'IPresultscareer [Back translation in English:]',
    'results [Back translation in English:]',
    'select [Back translation in English:]',
  ],
  tokenCol: 'Token',
  dateCol: 'Date last action',
  ip: 'IP address',
};

module.exports = conf;
